# Import Library

In [1]:
import pandas as pd

# Data Loading

In [2]:
menu = pd.read_csv('data/data_recipes_cleaned.csv')
menu.head()

,user_id,item_id,rating,URL,Category,Total Ingredients,Ingredients Cleaned,Total Steps,Steps Cleaned,Image URL,Title Cleaned,total_rating
0,1,2361,4,https://cookpad.com/id/resep/4353965-bandeng-b...,ikan,20,"ikan bandeng , jeruk nipis , merica bubuk , ga...",5,['step 1 bersihkan ikan belah melebar kucuri a...,https://img-global.cpcdn.com/recipes/ee089446e...,bandeng bakar tulang lunak,1.50
1,1,6558,5,https://cookpad.com/id/resep/3672469-sayur-gor...,sapi,13,"iga sapi tetelan enak sebenernya , kantong pla...",5,['step 1 rebus igatetelan hingga empuk sisihka...,https://img-global.cpcdn.com/recipes/343ded8b0...,sayur goreng asem iga sapi,3.33
2,1,12168,4,https://cookpad.com/id/resep/4030298-tumis-ped...,tempe,6,"jamur tiram , kotak tempe diiris dadu , bawang...",6,['step 1 cuci semua bahan bahan diatas lalu ha...,https://img-global.cpcdn.com/recipes/319b491c0...,tumis pedas jamur tempe,2.33
3,1,8872,3,https://cookpad.com/id/resep/4040408-oseng-cec...,tahu,18,"cecek , kotak tahu , bumbu , bawang putih , ba...",7,['step 1 cuci dan iris cecek potong kotak dan ...,https://img-global.cpcdn.com/recipes/8804b5fab...,oseng cecek dan tahu,1.33
4,1,12953,3,https://cookpad.com/id/resep/4384302-ikan-teri...,udang,10,"udang , ikan teri , bawang putih , bawang mera...",13,"['step 1 kupas kulit udang terlebih dahulu', '...",https://img-global.cpcdn.com/recipes/49cdc2b4f...,ikan teri udang,1.00

In [21]:
menu.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14945 entries, 0 to 14944
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Title                14945 non-null  object
 1   Ingredients          14945 non-null  object
 2   Steps                14945 non-null  object
 3   Loves                14945 non-null  int64
 4   URL                  14945 non-null  object
 5   Category             14945 non-null  object
 6   Title Cleaned        14925 non-null  object
 7   Total Ingredients    14945 non-null  int64
 8   Ingredients Cleaned  14945 non-null  object
 9   Total Steps          14945 non-null  int64
dtypes: int64(3), object(7)
memory usage: 1.1+ MB

In [22]:
menu.shape

(14945, 10)

# Data Preprocessing & Cleaning

In [23]:
# kolom drop: Ingredients, Steps, URL, Title, 
menu_fix = menu[['Title','Ingredients','Steps','URL', 'Title Cleaned', 'Category', 'Ingredients Cleaned', 'Total Ingredients', 'Total Steps', 'Loves']]
menu_fix.head()

,Title,Ingredients,Steps,URL,Title Cleaned,Category,Ingredients Cleaned,Total Ingredients,Total Steps,Loves
0,Ayam Woku Manado,1 Ekor Ayam Kampung (potong 12)--2 Buah Jeruk ...,1) Cuci bersih ayam dan tiriskan. Lalu peras j...,https://cookpad.com/id/resep/4473027-ayam-woku...,ayam woku manado,ayam,"ayam kampung potong , jeruk nipis , garam , ku...",14,7,1
1,Ayam goreng tulang lunak,1 kg ayam (dipotong sesuai selera jangan kecil...,"1) Haluskan bumbu2nya (BaPut, ketumbar, kemiri...",https://cookpad.com/id/resep/4471956-ayam-gore...,ayam goreng tulang lunak,ayam,"ayam dipotong , serai , daun jeruk , bawang pu...",11,5,1
2,Ayam cabai kawin,1/4 kg ayam--3 buah cabai hijau besar--7 buah ...,1) Panaskan minyak di dalam wajan. Setelah min...,https://cookpad.com/id/resep/4473057-ayam-caba...,ayam cabai kawin,ayam,"ayam , cabai hijau , cabai merah rawit , bawan...",10,3,2
3,Ayam Geprek,250 gr daging ayam (saya pakai fillet)--Secuku...,1) Goreng ayam seperti ayam krispi\n2) Ulek se...,https://cookpad.com/id/resep/4473023-ayam-geprek,ayam geprek,ayam,"daging ayam fillet , gula garam , tepung ayam ...",7,3,10
4,Minyak Ayam,400 gr kulit ayam & lemaknya--8 siung bawang p...,1) Cuci bersih kulit ayam. Sisihkan\n2) Ambil ...,https://cookpad.com/id/resep/4427438-minyak-ayam,minyak ayam,ayam,"kulit ayam & lemaknya , bawang putih , cincang...",5,6,4

In [24]:
menu_fix.isnull().sum()

Title                   0
Ingredients             0
Steps                   0
URL                     0
Title Cleaned          20
Category                0
Ingredients Cleaned     0
Total Ingredients       0
Total Steps             0
Loves                   0
dtype: int64

In [25]:
menu_fix.dropna(inplace=True)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_4908\2524654342.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  menu_fix.dropna(inplace=True)

In [26]:
menu_fix.isnull().sum()

Title                  0
Ingredients            0
Steps                  0
URL                    0
Title Cleaned          0
Category               0
Ingredients Cleaned    0
Total Ingredients      0
Total Steps            0
Loves                  0
dtype: int64

In [27]:
menu_fix.duplicated(subset='Title Cleaned').sum()

np.int64(3591)

In [28]:
menu_fix = menu_fix.drop_duplicates(subset='Title Cleaned', keep='first')

In [29]:
menu_fix.shape

(11334, 10)

In [30]:
menu_fix['Loves'].unique()

array([  1,   2,  10,   4,   0,   6,   8,   3,  46,  15,   7,  35,  67,
         9,  17,  21,  13, 164,  12,   5,  20,  33,  40,  30,  14,  11,
        69,  27,  45,  43,  22,  60,  25, 123,  36,  82,  31,  16,  80,
        24,  53,  44,  71,  18,  63,  49,  83,  92,  89,  32, 116,  39,
        23,  51,  47,  50, 130,  79,  58,  29,  38,  68,  85,  57,  65,
        72,  26,  77,  59,  56, 170,  28,  34,  62,  96, 155,  41, 151,
        37,  91, 166,  75,  94,  52, 108,  55, 516, 242,  19,  90,  88,
        54, 100,  86,  61,  48, 188, 117,  42,  97, 196,  64, 134,  66,
       112, 126,  84, 168, 113, 153, 143,  87, 105,  81, 241, 103, 342,
       249,  70,  98,  74, 180, 171, 145, 147, 195, 121, 375, 111, 133,
       142, 118, 939, 135, 269, 127, 119, 106, 132,  78, 481, 115, 120,
        76, 129, 102, 107, 104, 150, 245, 160, 167, 172, 158, 144,  73,
       109])

In [31]:
# Buat function untuk mengubah loves menjadi rating
def loves_to_rating(loves):
    if loves < 5:
        return 1
    elif loves < 10:
        return 2
    elif loves < 30:
        return 3
    elif loves < 100:
        return 4
    else:
        return 5

menu_fix['Rating'] = menu_fix['Loves'].apply(loves_to_rating)

In [32]:
menu_fix = menu_fix.drop(columns=['Loves'])
menu_fix

,Title,Ingredients,Steps,URL,Title Cleaned,Category,Ingredients Cleaned,Total Ingredients,Total Steps,Rating
0,Ayam Woku Manado,1 Ekor Ayam Kampung (potong 12)--2 Buah Jeruk ...,1) Cuci bersih ayam dan tiriskan. Lalu peras j...,https://cookpad.com/id/resep/4473027-ayam-woku...,ayam woku manado,ayam,"ayam kampung potong , jeruk nipis , garam , ku...",14,7,1
1,Ayam goreng tulang lunak,1 kg ayam (dipotong sesuai selera jangan kecil...,"1) Haluskan bumbu2nya (BaPut, ketumbar, kemiri...",https://cookpad.com/id/resep/4471956-ayam-gore...,ayam goreng tulang lunak,ayam,"ayam dipotong , serai , daun jeruk , bawang pu...",11,5,1
2,Ayam cabai kawin,1/4 kg ayam--3 buah cabai hijau besar--7 buah ...,1) Panaskan minyak di dalam wajan. Setelah min...,https://cookpad.com/id/resep/4473057-ayam-caba...,ayam cabai kawin,ayam,"ayam , cabai hijau , cabai merah rawit , bawan...",10,3,1
3,Ayam Geprek,250 gr daging ayam (saya pakai fillet)--Secuku...,1) Goreng ayam seperti ayam krispi\n2) Ulek se...,https://cookpad.com/id/resep/4473023-ayam-geprek,ayam geprek,ayam,"daging ayam fillet , gula garam , tepung ayam ...",7,3,3
4,Minyak Ayam,400 gr kulit ayam & lemaknya--8 siung bawang p...,1) Cuci bersih kulit ayam. Sisihkan\n2) Ambil ...,https://cookpad.com/id/resep/4427438-minyak-ayam,minyak ayam,ayam,"kulit ayam & lemaknya , bawang putih , cincang...",5,6,1
...,...,...,...,...,...,...,...,...,...,...
14938,Ote-ote udang teri crispy,Bahan Ote-ote--250 g tepung terigu--150 ml air...,1) Cara membuat adonan\n2) Daun bawang dan baw...,https://cookpad.com/id/resep/3795572-ote-ote-u...,ote ote udang teri crispy,udang,"ote ote , tepung terigu , air , daun bawang , ...",13,11,2
14939,Udang tepung dengan saus kecap,Bahan:--300 gr Udang--1 btr Telur--Bumbu:--3 t...,1) Siapkan wadah untuk 1tepung sajiku beri air...,https://cookpad.com/id/resep/3795600-udang-tep...,udang tepung saus kecap,udang,"udang , telur , bumbu , tepung sajiku seribuan...",10,6,3
14941,Jipang tumis udang,500 gr jipang(saya pk 6bh jipang muda yg kecil...,1) Tumis bawang merah bawang putih hingga haru...,https://cookpad.com/id/resep/3795267-jipang-tu...,jipang tumis udang,udang,"jipang jipang muda , potong korek api , bawang...",10,5,2
14942,Tumis Udang Tempe,3 siung bawang merah--3 siung bawang putih--2 ...,"1) Tiriskan bawang putih, bawang merah dan cab...",https://cookpad.com/id/resep/3794945-tumis-uda...,tumis udang tempe,udang,"bawang merah , bawang putih , cabe rawit , tom...",9,5,1
14943,Tumis kacang panjang terong udang,"Stgah ikat kacang panjang,ku bli 3ribu d psr--...","1) Potong2 kacang panjang,terong cuci bersih s...",https://cookpad.com/id/resep/3794623-tumis-kac...,tumis kacang panjang terong udang,udang,"kacang panjang , terong bulat , udang sisa kul...",10,3,3

In [33]:
menu_fix['Category'] = menu_fix['Category'].str.capitalize()

In [34]:
# Buat kolom function untuk menggabungkan kolom total ingredients dan total steps
# Setelah itu buat kolom baru bernama 'Complexity'

def classify_complexity(steps, ingredients):
    if ingredients <= 9 and steps <= 4:
        return 'Cepat & Mudah'
    elif ingredients <= 15 and steps <= 7:
        return 'Butuh Usaha'
    else:
        return 'Level Dewa Masak'

menu_fix['Complexity'] = menu_fix.apply(lambda x: classify_complexity(x['Total Steps'], x['Total Ingredients']), axis=1)
menu_fix = menu_fix.drop(columns=['Total Ingredients', 'Total Steps'])
menu_fix

,Title,Ingredients,Steps,URL,Title Cleaned,Category,Ingredients Cleaned,Rating,Complexity
0,Ayam Woku Manado,1 Ekor Ayam Kampung (potong 12)--2 Buah Jeruk ...,1) Cuci bersih ayam dan tiriskan. Lalu peras j...,https://cookpad.com/id/resep/4473027-ayam-woku...,ayam woku manado,Ayam,"ayam kampung potong , jeruk nipis , garam , ku...",1,Butuh Usaha
1,Ayam goreng tulang lunak,1 kg ayam (dipotong sesuai selera jangan kecil...,"1) Haluskan bumbu2nya (BaPut, ketumbar, kemiri...",https://cookpad.com/id/resep/4471956-ayam-gore...,ayam goreng tulang lunak,Ayam,"ayam dipotong , serai , daun jeruk , bawang pu...",1,Butuh Usaha
2,Ayam cabai kawin,1/4 kg ayam--3 buah cabai hijau besar--7 buah ...,1) Panaskan minyak di dalam wajan. Setelah min...,https://cookpad.com/id/resep/4473057-ayam-caba...,ayam cabai kawin,Ayam,"ayam , cabai hijau , cabai merah rawit , bawan...",1,Butuh Usaha
3,Ayam Geprek,250 gr daging ayam (saya pakai fillet)--Secuku...,1) Goreng ayam seperti ayam krispi\n2) Ulek se...,https://cookpad.com/id/resep/4473023-ayam-geprek,ayam geprek,Ayam,"daging ayam fillet , gula garam , tepung ayam ...",3,Cepat & Mudah
4,Minyak Ayam,400 gr kulit ayam & lemaknya--8 siung bawang p...,1) Cuci bersih kulit ayam. Sisihkan\n2) Ambil ...,https://cookpad.com/id/resep/4427438-minyak-ayam,minyak ayam,Ayam,"kulit ayam & lemaknya , bawang putih , cincang...",1,Butuh Usaha
...,...,...,...,...,...,...,...,...,...
14938,Ote-ote udang teri crispy,Bahan Ote-ote--250 g tepung terigu--150 ml air...,1) Cara membuat adonan\n2) Daun bawang dan baw...,https://cookpad.com/id/resep/3795572-ote-ote-u...,ote ote udang teri crispy,Udang,"ote ote , tepung terigu , air , daun bawang , ...",2,Level Dewa Masak
14939,Udang tepung dengan saus kecap,Bahan:--300 gr Udang--1 btr Telur--Bumbu:--3 t...,1) Siapkan wadah untuk 1tepung sajiku beri air...,https://cookpad.com/id/resep/3795600-udang-tep...,udang tepung saus kecap,Udang,"udang , telur , bumbu , tepung sajiku seribuan...",3,Butuh Usaha
14941,Jipang tumis udang,500 gr jipang(saya pk 6bh jipang muda yg kecil...,1) Tumis bawang merah bawang putih hingga haru...,https://cookpad.com/id/resep/3795267-jipang-tu...,jipang tumis udang,Udang,"jipang jipang muda , potong korek api , bawang...",2,Butuh Usaha
14942,Tumis Udang Tempe,3 siung bawang merah--3 siung bawang putih--2 ...,"1) Tiriskan bawang putih, bawang merah dan cab...",https://cookpad.com/id/resep/3794945-tumis-uda...,tumis udang tempe,Udang,"bawang merah , bawang putih , cabe rawit , tom...",1,Butuh Usaha
14943,Tumis kacang panjang terong udang,"Stgah ikat kacang panjang,ku bli 3ribu d psr--...","1) Potong2 kacang panjang,terong cuci bersih s...",https://cookpad.com/id/resep/3794623-tumis-kac...,tumis kacang panjang terong udang,Udang,"kacang panjang , terong bulat , udang sisa kul...",3,Butuh Usaha

In [35]:
menu_fix['tags'] = menu_fix['Title Cleaned'] + ', ' + menu_fix['Category'] + ', ' + menu_fix['Ingredients Cleaned'] + menu_fix['Complexity']
menu_fix_banget = menu_fix.drop(columns=['Title Cleaned', 'Ingredients Cleaned', 'Category', 'Complexity'])
menu_fix_banget

,Title,Ingredients,Steps,URL,Rating,tags
0,Ayam Woku Manado,1 Ekor Ayam Kampung (potong 12)--2 Buah Jeruk ...,1) Cuci bersih ayam dan tiriskan. Lalu peras j...,https://cookpad.com/id/resep/4473027-ayam-woku...,1,"ayam woku manado, Ayam, ayam kampung potong , ..."
1,Ayam goreng tulang lunak,1 kg ayam (dipotong sesuai selera jangan kecil...,"1) Haluskan bumbu2nya (BaPut, ketumbar, kemiri...",https://cookpad.com/id/resep/4471956-ayam-gore...,1,"ayam goreng tulang lunak, Ayam, ayam dipotong ..."
2,Ayam cabai kawin,1/4 kg ayam--3 buah cabai hijau besar--7 buah ...,1) Panaskan minyak di dalam wajan. Setelah min...,https://cookpad.com/id/resep/4473057-ayam-caba...,1,"ayam cabai kawin, Ayam, ayam , cabai hijau , c..."
3,Ayam Geprek,250 gr daging ayam (saya pakai fillet)--Secuku...,1) Goreng ayam seperti ayam krispi\n2) Ulek se...,https://cookpad.com/id/resep/4473023-ayam-geprek,3,"ayam geprek, Ayam, daging ayam fillet , gula g..."
4,Minyak Ayam,400 gr kulit ayam & lemaknya--8 siung bawang p...,1) Cuci bersih kulit ayam. Sisihkan\n2) Ambil ...,https://cookpad.com/id/resep/4427438-minyak-ayam,1,"minyak ayam, Ayam, kulit ayam & lemaknya , baw..."
...,...,...,...,...,...,...
14938,Ote-ote udang teri crispy,Bahan Ote-ote--250 g tepung terigu--150 ml air...,1) Cara membuat adonan\n2) Daun bawang dan baw...,https://cookpad.com/id/resep/3795572-ote-ote-u...,2,"ote ote udang teri crispy, Udang, ote ote , te..."
14939,Udang tepung dengan saus kecap,Bahan:--300 gr Udang--1 btr Telur--Bumbu:--3 t...,1) Siapkan wadah untuk 1tepung sajiku beri air...,https://cookpad.com/id/resep/3795600-udang-tep...,3,"udang tepung saus kecap, Udang, udang , telur ..."
14941,Jipang tumis udang,500 gr jipang(saya pk 6bh jipang muda yg kecil...,1) Tumis bawang merah bawang putih hingga haru...,https://cookpad.com/id/resep/3795267-jipang-tu...,2,"jipang tumis udang, Udang, jipang jipang muda ..."
14942,Tumis Udang Tempe,3 siung bawang merah--3 siung bawang putih--2 ...,"1) Tiriskan bawang putih, bawang merah dan cab...",https://cookpad.com/id/resep/3794945-tumis-uda...,1,"tumis udang tempe, Udang, bawang merah , bawan..."
14943,Tumis kacang panjang terong udang,"Stgah ikat kacang panjang,ku bli 3ribu d psr--...","1) Potong2 kacang panjang,terong cuci bersih s...",https://cookpad.com/id/resep/3794623-tumis-kac...,3,"tumis kacang panjang terong udang, Udang, kaca..."

# Stemming dengan Sastrawi

In [36]:
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

factory = StemmerFactory()
stemmer = factory.create_stemmer()

menu_fix_banget['tags_stemmer'] = menu_fix_banget['tags'].apply(lambda x: ' '.join([stemmer.stem(word) for word in x.split(', ')]))

# TF-IDF Vectorization

In [37]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(menu_fix_banget['tags_stemmer'])

# Cosine Similarity

In [38]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_sim = cosine_similarity(tfidf_matrix)

# Fungsi Rekomendasi

In [39]:
def recommend_from_keyword(ingredients_list, top_n=10, min_rating=None, max_rating=None, complexity_filter=None):
    # Gabungkan semua bahan jadi satu string
    combined_ingredients = ' '.join(ingredients_list)
    stemmed_ingredients = ' '.join([stemmer.stem(word) for word in combined_ingredients.split()])
    
    # 2. TF-IDF vector untuk keyword
    keyword_vector = vectorizer.transform([stemmed_ingredients])
    
    # 3. Hitung similarity
    sim_scores = cosine_similarity(keyword_vector, tfidf_matrix).flatten()
    
    # 4. Ambil top_n * 2 hasil teratas (biar bisa difilter)
    top_indices = sim_scores.argsort()[::-1]
    
    results = menu_fix.iloc[top_indices].copy()
    results['similarity'] = sim_scores[top_indices]
    
    # 5. Filter opsional
    if min_rating is not None:
        results = results[results['Rating'] >= min_rating]
    if max_rating is not None:
        results = results[results['Rating'] <= max_rating]
    if complexity_filter:
        results = results[results['Complexity'] == complexity_filter]
    
    # 6. Return hasil top_n
    return results[['Title','Category','Ingredients', 'Steps', 'URL', 'Rating', 'Complexity']].head(top_n)

In [41]:
# Contoh
Top_10_olahan_telor_simple = recommend_from_keyword(
    ingredients_list=['Telur', 'Ayam'],
    top_n=10,
    complexity_filter='Cepat & Mudah',
    min_rating=4,
    max_rating=5
)
Top_10_olahan_telor_simple

,Title,Category,Ingredients,Steps,URL,Rating,Complexity
10599,🌶 telur sambal ijo 🌶,Telur,1/2 kg telur--200 gr cabai hijau--1 buah tomat...,"1) Rebus telur sampai matang, lalu kupas dan g...",https://cookpad.com/id/resep/3966969-%F0%9F%8C...,4,Cepat & Mudah
10511,Telur balado ala kost,Telur,3 buah telur--10 cabe keriting besar--1 buah t...,"1) Rebus telur\n2) Ulek bawang merah, putih, c...",https://cookpad.com/id/resep/3984342-telur-bal...,4,Cepat & Mudah
10647,Telur Dadar lembut,Telur,2 Butir Telur Ayam--4 sdm tepung serbaguna (ko...,1) Campur tepung dan air di aduk sampai lembut...,https://cookpad.com/id/resep/3957705-telur-dad...,4,Cepat & Mudah
10029,Telur rebus sambal tomat,Telur,2 buah telur--1 bawang merah--1 bawang putih--...,"1) Pertama rebus telur, lalu belah menjadi 2 b...",https://cookpad.com/id/resep/4199476-telur-reb...,4,Cepat & Mudah
9892,Buncis Orak Arik Telur Nyammii,Telur,1 Butir Telur Ayam--1/4 kgs Buncis--2 Siung Ba...,1) Bersihkan dahulu buncis sblm dipotong\n2) T...,https://cookpad.com/id/resep/4245257-buncis-or...,4,Cepat & Mudah
275,Bakwan goreng ayam,Ayam,100 gr dada ayam giling--4 sdm tepung tapioka-...,"1) Campurkan semua bahan, lalu goreng dalam mi...",https://cookpad.com/id/resep/4455545-bakwan-go...,4,Cepat & Mudah
9246,Dadar Tahu Telur,Telur,"1 buah tahu putih--2 butir telur, kocok lepas-...",1) Hancurkan tahu dg garpu. Campur telur dg se...,https://cookpad.com/id/resep/4447453-dadar-tah...,5,Cepat & Mudah
9723,Telor glundung balado #ketopad_cp_telor,Telur,5 butir telur ayam--Bumbu halus--5 siung bawan...,"1) Rebus telor ayam sampai matang,lalu kupas.....",https://cookpad.com/id/resep/4287894-telor-glu...,4,Cepat & Mudah
686,Sop ayam simple,Ayam,1 tangkai brokoli--1 buah wortel--1 batang dau...,"1) Cuci bersih ayam. Potong wortel, brokoli, d...",https://cookpad.com/id/resep/4422589-sop-ayam-...,4,Cepat & Mudah
9560,Tumis Telur Kentang Kecap (irit ekonomis dan e...,Telur,"4 btr telur ayam--2 buah kentang Medan, kupas ...","1) Buat telur mata sapi dan goreng kentang, si...",https://cookpad.com/id/resep/4317544-tumis-tel...,4,Cepat & Mudah

In [42]:
# Jika ada kolom penghubung, misalnya 'Title'
merged_df = menu_fix.merge(menu_fix_banget[['Title', 'tags_stemmer']], on='Title', how='left')

In [43]:
merged_df.head()

,Title,Ingredients,Steps,URL,Title Cleaned,Category,Ingredients Cleaned,Rating,Complexity,tags,tags_stemmer
0,Ayam Woku Manado,1 Ekor Ayam Kampung (potong 12)--2 Buah Jeruk ...,1) Cuci bersih ayam dan tiriskan. Lalu peras j...,https://cookpad.com/id/resep/4473027-ayam-woku...,ayam woku manado,Ayam,"ayam kampung potong , jeruk nipis , garam , ku...",1,Butuh Usaha,"ayam woku manado, Ayam, ayam kampung potong , ...",ayam woku manado ayam ayam kampung potong jeru...
1,Ayam goreng tulang lunak,1 kg ayam (dipotong sesuai selera jangan kecil...,"1) Haluskan bumbu2nya (BaPut, ketumbar, kemiri...",https://cookpad.com/id/resep/4471956-ayam-gore...,ayam goreng tulang lunak,Ayam,"ayam dipotong , serai , daun jeruk , bawang pu...",1,Butuh Usaha,"ayam goreng tulang lunak, Ayam, ayam dipotong ...",ayam goreng tulang lunak ayam ayam potong sera...
2,Ayam cabai kawin,1/4 kg ayam--3 buah cabai hijau besar--7 buah ...,1) Panaskan minyak di dalam wajan. Setelah min...,https://cookpad.com/id/resep/4473057-ayam-caba...,ayam cabai kawin,Ayam,"ayam , cabai hijau , cabai merah rawit , bawan...",1,Butuh Usaha,"ayam cabai kawin, Ayam, ayam , cabai hijau , c...",ayam cabai kawin ayam ayam cabai hijau cabai m...
3,Ayam Geprek,250 gr daging ayam (saya pakai fillet)--Secuku...,1) Goreng ayam seperti ayam krispi\n2) Ulek se...,https://cookpad.com/id/resep/4473023-ayam-geprek,ayam geprek,Ayam,"daging ayam fillet , gula garam , tepung ayam ...",3,Cepat & Mudah,"ayam geprek, Ayam, daging ayam fillet , gula g...",ayam geprek ayam daging ayam fillet gula garam...
4,Minyak Ayam,400 gr kulit ayam & lemaknya--8 siung bawang p...,1) Cuci bersih kulit ayam. Sisihkan\n2) Ambil ...,https://cookpad.com/id/resep/4427438-minyak-ayam,minyak ayam,Ayam,"kulit ayam & lemaknya , bawang putih , cincang...",1,Butuh Usaha,"minyak ayam, Ayam, kulit ayam & lemaknya , baw...",minyak ayam ayam kulit ayam lemak bawang putih...

In [44]:
import pickle
import json
import numpy as np
import pandas as pd
from scipy.sparse import save_npz, load_npz
import gzip
import os

# %%
print("Menyimpan model dan data dengan optimisasi...")

# Buat direktori models jika belum ada
os.makedirs('models', exist_ok=True)

# %%
# 1. Simpan TF-IDF Vectorizer (tetap dalam format pickle karena ukurannya kecil)
print("Saving TF-IDF Vectorizer...")
with open('models/tfidf_vectorizer.pkl', 'wb') as f:
    pickle.dump(vectorizer, f)

# %%
# 2. OPTIMISASI: Simpan hanya data penting dari Cosine Similarity Matrix
# Alih-alih menyimpan matrix penuh, kita simpan dalam format sparse dan compressed
print("Saving optimized Cosine Similarity Matrix...")

# Konversi ke sparse matrix (hanya simpan nilai > threshold tertentu)
threshold = 0.1  # Hanya simpan similarity > 0.1
cosine_sim_sparse = cosine_sim.copy()
cosine_sim_sparse[cosine_sim_sparse < threshold] = 0

# Simpan dalam format compressed sparse
from scipy.sparse import csr_matrix
cosine_sparse = csr_matrix(cosine_sim_sparse)
save_npz('models/cosine_similarity_sparse.npz', cosine_sparse)

print(f"Original cosine matrix size: {cosine_sim.nbytes / (1024*1024):.2f} MB")
print(f"Sparse matrix file size: {os.path.getsize('models/cosine_similarity_sparse.npz') / (1024*1024):.2f} MB")

# %%
# 3. Simpan DataFrame dalam format compressed CSV
print("Saving processed recipes...")
menu_fix.to_csv('models/processed_recipes.csv.gz', index=False, compression='gzip')

# %%
# 4. Simpan stemmer (ukuran kecil, keep as is)
print("Saving stemmer...")
with open('models/stemmer.pkl', 'wb') as f:
    pickle.dump(stemmer, f)

# %%
# 5. OPTIMISASI: Simpan data minimal dalam JSON compressed
def save_optimized_json():
    print("Creating optimized JSON files...")
    
    # Hanya simpan data essential untuk recipes
    recipes_json = []
    for idx, row in merged_df.iterrows():
        recipe = {
            'id': str(idx),
            'title': row['Title'],
            'category': row['Category'],
            'rating': int(row['Rating']),
            'complexity': row['Complexity'],
            'tags': row['tags']
        }
        # Simpan ingredients dan steps dalam format compact
        if isinstance(row['Ingredients'], str):
            recipe['ingredients'] = row['Ingredients']
        if isinstance(row['Steps'], str):
            recipe['steps'] = row['Steps']
        if isinstance(row['URL'], str):
            recipe['url'] = row['URL']
            
        recipes_json.append(recipe)
    
    # Simpan dalam format compressed JSON
    with gzip.open('models/recipes.json.gz', 'wt', encoding='utf-8') as f:
        json.dump(recipes_json, f, ensure_ascii=False, separators=(',', ':'))
    
    # Simpan vocabulary dalam format minimal
    tfidf_vocab = {
        'vocabulary': vectorizer.vocabulary_,
        'feature_names': vectorizer.get_feature_names_out().tolist()
    }
    
    with gzip.open('models/tfidf_vocab.json.gz', 'wt', encoding='utf-8') as f:
        json.dump(tfidf_vocab, f, separators=(',', ':'))
    
    print("Optimized JSON files created!")

# %%
# 6. ELIMINASI: Skip cosine_matrix.json karena terlalu besar
# Kita akan hitung similarity on-the-fly menggunakan TF-IDF
print("Skipping large cosine_matrix.json - will compute on-the-fly")

# Jalankan optimisasi
save_optimized_json()

# %%
# 7. Print ukuran file untuk monitoring
print("\n=== FILE SIZES ===")
model_files = [
    'models/tfidf_vectorizer.pkl',
    'models/cosine_similarity_sparse.npz',
    'models/processed_recipes.csv.gz',
    'models/stemmer.pkl',
    'models/recipes.json.gz',
    'models/tfidf_vocab.json.gz'
]

total_size = 0
for file_path in model_files:
    if os.path.exists(file_path):
        size_mb = os.path.getsize(file_path) / (1024*1024)
        print(f"{file_path}: {size_mb:.2f} MB")
        total_size += size_mb
    else:
        print(f"{file_path}: FILE NOT FOUND")

print(f"\nTotal model size: {total_size:.2f} MB")

if total_size > 900:  # Buffer 100MB dari limit 1GB
    print("⚠️  WARNING: Total size might be too large for HF Spaces!")
    print("Consider further optimization or use Git LFS")
else:
    print("✅ Model size is suitable for HF Spaces")

print("\nModel optimization completed!")

# %%
# 8. Optional: Hapus file besar yang tidak diperlukan
print("\nCleaning up large unnecessary files...")
files_to_remove = [
    'models/cosine_matrix.json',  # File ini sangat besar
    'models/cosine_similarity_matrix.pkl'  # Kita sudah punya versi sparse
]

for file_path in files_to_remove:
    if os.path.exists(file_path):
        size_mb = os.path.getsize(file_path) / (1024*1024)
        os.remove(file_path)
        print(f"Removed {file_path} ({size_mb:.2f} MB)")

print("Cleanup completed!")

Menyimpan model dan data dengan optimisasi...
Saving TF-IDF Vectorizer...
Saving optimized Cosine Similarity Matrix...
Original cosine matrix size: 980.07 MB
Sparse matrix file size: 290.11 MB
Saving processed recipes...
Saving stemmer...
Skipping large cosine_matrix.json - will compute on-the-fly
Creating optimized JSON files...
Optimized JSON files created!

=== FILE SIZES ===
models/tfidf_vectorizer.pkl: 0.16 MB
models/cosine_similarity_sparse.npz: 290.11 MB
models/processed_recipes.csv.gz: 3.40 MB
models/stemmer.pkl: 0.45 MB
models/recipes.json.gz: 3.29 MB
models/tfidf_vocab.json.gz: 0.07 MB

Total model size: 297.49 MB
✅ Model size is suitable for HF Spaces

Model optimization completed!

Cleaning up large unnecessary files...
Cleanup completed!